title: "Christian Adrian Aceves Perez | Ciberseguridad & SecOps"
email: "caap.222@gmail.com"
description: "Portafolio profesional de Ciberseguridad, SecOps, Writeups de HTB/THM y Herramientas Open Source por Christian Adrian Aceves Perez (caap1234)."
baseurl: ""
url: "https://caap1234.github.io"
author: "Christian Adrian Aceves Perez"
github_username: "caap1234"
linkedin_username: "christian-adrian-aceves-perez"
htb_profile_url: "https://profile.hackthebox.com/profile/01a11c46-70c7-72a2-9a6a-a3a01f65b2f9?utm_medium=copy_url"
tryhackme_profile: "Qw3rty"

collections:
  writeups:
    output: true
    permalink: /writeups/:name/
  tools:
    output: true
    permalink: /tools/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "writeups"
    values:
      layout: "writeup"
  - scope:
      path: ""
      type: "tools"
    values:
      layout: "tool"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
